### ISSUE TITLE
MAME-related systems crash when software list is set

### ISSUE THREAD

**Issue by Smelltastic** [knulli-cfw/distribution#216]
### Knulli build version

firefly 2024/12/04 03:10 [ou]

### Your architecture

RG40XXV

### Issue description

UPDATE: Using the updated workaround and MAME 0.268, I'm not seeing any crashes UNLESS I set a software list option. Games still crash when I set a software list, and that may be required for some games, so I think the issue may still need addressing.

-----

After implementing the MAME workaround from https://github.com/knulli-cfw/distribution/issues/169, some systems that use software list (I'm trying BBC Micro) still crash. Error log shows:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/mame/hash/bbc_cass.xml'

I found the relevant file at:
/usr/share/lr-mame/hash/bbc_cass.xml

As a workaround, I was able to get it running on my system by linking the expected hash folder:

ln -s /usr/share/lr-mame/hash /usr/bin/mame/hash
batocera-save-overlay

### Detailed reproduction steps

First replace mame_libretro.so with the one from the 2024/07/21 release per https://github.com/knulli-cfw/distribution/issues/169.
Try to launch any BBC Micro game and it will crash back to ES.
Set Software List to anything other than "Auto" or "None" and try again, will still crash but the log will reference the missing software list xml.

### Details of any attempts to fix this yourself

ln -s /usr/share/lr-mame/hash /usr/bin/mame/hash
batocera-save-overlay

### Details of any modifications you have made to Knulli.

None

### Logs and data

es_launch_stderr.log:

error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
evmapy: no process found
Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 456, in <module>
    do_new_context(new_context_name, new_context_json)
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 458, in <module>
    do_new_context()
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
2024-12-13 13:41:27,228 ERROR (emulatorlauncher.py:562):launch configgen exception: 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/configgen/emulatorlauncher.py", line 560, in launch
    exitcode = main(args, maxnbplayers)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/configgen/emulatorlauncher.py", line 57, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/configgen/emulatorlauncher.py", line 210, in start_rom
    cmd = generator.generate(system, rom, player_controllers, metadata, guns, wheels, gameResolution)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/configgen/generators/libretro/libretroGenerator.py", line 125, in generate
    libretroConfig.writeLibretroConfig(self, retroconfig, system, playersControllers, metadata, guns, wheels, rom_path, bezel, shaderBezel, gameResolution, gfxBackend)
  File "/usr/lib/python3.11/site-packages/configgen/generators/libretro/libretroConfig.py", line 106, in writeLibretroConfig
    writeLibretroConfigToFile(retroconfig, createLibretroConfig(generator, system, controllers, metadata, guns, wheels, rom, bezel, shaderBezel, gameResolution, gfxBackend))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/configgen/generators/libretro/libretroConfig.py", line 130, in createLibretroConfig
    libretroMAMEConfig.generateMAMEConfigs(controllers, system, rom, guns)
  File "/usr/lib/python3.11/site-packages/configgen/generators/libretro/libretroMAMEConfig.py", line 199, in generateMAMEConfigs
    prepSoftwareList(subdirSoftList, softList, softDir, BIOS / "mame" / "hash", rom.parent)
  File "/usr/lib/python3.11/site-packages/configgen/generators/libretro/libretroMAMEConfig.py", line 473, in prepSoftwareList
    shutil.copy2(Path("/usr/bin/mame/hash") / f"{softList}.xml", hashDir / f"{softList}.xml")
  File "/usr/lib/python3.11/shutil.py", line 448, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/mame/hash/bbc_cass.xml'

**Comment by Zxquad** [comment]
Same kind of error here with Atom on KNULLI FIREFLY

error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
evmapy: aucun processus trouvé
Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 456, in <module>
    do_new_context(new_context_name, new_context_json)
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
2024-12-15 21:13:05,605 ERROR (emulatorlauncher.py:504):runCommand [INFO] === Build =======================================
[INFO] Capacités: ASIMD 
[INFO] Version: 1.19.1
[INFO] Built: Dec  4 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[ERROR] Couldn't find any cloud sync driver named ""
[INFO] Available cloud sync drivers are:
[INFO] 	webdav
[INFO] 	null
[WARN] Going to default to first cloud sync driver...
[INFO] [Core]: Loading dynamic libretro core from: "/usr/lib/libretro/mame_libretro.so"
[INFO] [Overrides]: Redirection du fichier de sauvegarde vers "/userdata/saves/atom/jsw.srm".
[INFO] [Overrides]: Redirection du fichier de sauvegarde instantanée vers "/userdata/saves/atom/jsw.state".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "2".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Environ]: GET_LED_INTERFACE.
[INFO] [Remaps]: common remap found at "/userdata/system/configs/retroarch/config/remaps/common/common.rmp".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/userdata/bios/".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "/userdata/system/configs/retroarch/downloads".
[INFO] [Environ]: SAVE_DIRECTORY: "/userdata/saves/atom".
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[libretro INFO] ------------------------
[libretro INFO] MAME 0.268 (unknown)
[libretro INFO] ------------------------
[INFO] [Content]: Chargement du contenu ignoré. L'implémentation va le charger elle-même.
[libretro INFO] Starting game from cmd: "atom -flop1 "/userdata/roms/atom/jsw.zip" -rompath "/userdata/roms/atom;/userdata/bios/" -ui_active -cfg_directory /userdata/saves/mame/cfg/atom -inipath /userdata/saves/mame/mame/ini -artpath /var/run/mame_artwork/;/usr/bin/mame/artwork/;/userdata/bios/lr-mame/artwork;/userdata/bios/mame/artwork;/userdata/decorations -artwork_crop -pluginspath /usr/bin/mame/plugins/;/userdata/saves/mame/plugins -homepath /userdata/saves/mame/plugins -samplepath /userdata/bios/mame/samples"
[libretro WARN] Parse path failed: "/userdata/bios/mame/samples"
[libretro INFO] Game name: atom
[libretro INFO] Game description: Atom

Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 458, in <module>
    do_new_context()
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'

**Comment by theVanZan** [comment]
Trying to get VC4000 games to work and think I'm getting the same error:

```
error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
evmapy: no process found
Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 456, in <module>
    do_new_context(new_context_name, new_context_json)
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
2024-12-16 23:14:16,550 ERROR (emulatorlauncher.py:504):runCommand [INFO] === Build =======================================
[INFO] Capabilities: ASIMD 
[INFO] Version: 1.19.1
[INFO] Built: Dec  4 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[ERROR] Couldn't find any cloud sync driver named ""
[INFO] Available cloud sync drivers are:
[INFO] 	webdav
[INFO] 	null
[WARN] Going to default to first cloud sync driver...
[INFO] [Core]: Loading dynamic libretro core from: "/usr/lib/libretro/mame_libretro.so"
[INFO] [Overrides]: Redirecting save file to "/userdata/saves/vc4000/carraces.srm".
[INFO] [Overrides]: Redirecting save state to "/userdata/saves/vc4000/carraces.state".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "30".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Environ]: GET_LED_INTERFACE.
[INFO] [Remaps]: common remap found at "/userdata/system/configs/retroarch/config/remaps/common/common.rmp".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/userdata/bios/".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "/userdata/system/configs/retroarch/downloads".
[INFO] [Environ]: SAVE_DIRECTORY: "/userdata/saves/vc4000".
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[libretro INFO] ------------------------
[libretro INFO] MAME 0.268 (unknown)
[libretro INFO] ------------------------
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] Starting game from cmd: "vc4000 -cart "/userdata/roms/vc4000/carraces.zip" -rompath "/userdata/roms/vc4000;/userdata/bios/" -ui_active -cfg_directory /userdata/saves/mame/cfg/vc4000 -inipath /userdata/saves/mame/mame/ini -artpath /var/run/mame_artwork/;/usr/bin/mame/artwork/;/userdata/bios/lr-mame/artwork;/userdata/bios/mame/artwork;/userdata/decorations -artwork_crop -pluginspath /usr/bin/mame/plugins/;/userdata/saves/mame/plugins -homepath /userdata/saves/mame/plugins -samplepath /userdata/bios/mame/samples"
[libretro WARN] Parse path failed: "/userdata/bios/mame/samples"
[libretro INFO] Game name: vc4000
[libretro INFO] Game description: Interton Electronic VC 4000

Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 458, in <module>
    do_new_context()
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
```

**Comment by bbilford83** [comment]
Fairly certain I am having the same problem with fmtowns on Knulli Firefly.  

[INFO] Capabilities: ASIMD 
[INFO] Version: 1.19.1
[INFO] Built: Dec  4 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[ERROR] Couldn't find any cloud sync driver named ""
[INFO] Available cloud sync drivers are:
[INFO] 	webdav
[INFO] 	null
[WARN] Going to default to first cloud sync driver...
[INFO] [Core]: Loading dynamic libretro core from: "/usr/lib/libretro/mame_libretro.so"
[INFO] [Overrides]: Redirecting save file to "/userdata/saves/fmtowns/Afterburner (1987)(Sega)(Jp-En).srm".
[INFO] [Overrides]: Redirecting save state to "/userdata/saves/fmtowns/Afterburner (1987)(Sega)(Jp-En).state".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Core]: Folder-specific core options found at "/userdata/system/configs/retroarch/config/MAME/cmdfiles.opt".
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Environ]: GET_LED_INTERFACE.
[INFO] [Remaps]: common remap found at "/userdata/system/configs/retroarch/config/remaps/common/common.rmp".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/userdata/bios/".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "/userdata/system/configs/retroarch/downloads".
[INFO] [Environ]: SAVE_DIRECTORY: "/userdata/saves/fmtowns".
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_KEYBOARD_CALLBACK.
[libretro INFO] ------------------------
[libretro INFO] MAME 0.265 (unknown)
[libretro INFO] ------------------------
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[libretro INFO] Starting game from cmd: "fmtmarty fmtowns -rompath "/var/run/mame_software;/userdata/bios/" -swpath /var/run/mame_software -verbose -ui_active -cfg_directory /userdata/saves/mame/cfg/fmtmarty -inipath /userdata/saves/mame/mame/ini -artpath /var/run/mame_artwork/;/usr/bin/mame/artwork/;/userdata/bios/lr-mame/artwork;/userdata/bios/mame/artwork;/userdata/decorations -artwork_crop -pluginspath /usr/bin/mame/plugins/;/userdata/saves/mame/plugins -homepath /userdata/saves/mame/plugins -samplepath /userdata/bios/mame/samples"
[libretro WARN] Parse path failed: "/userdata/bios/mame/samples"
[libretro INFO] Game name: fmtmarty
[libretro INFO] Game description: FM-Towns Marty

Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 458, in <module>
    do_new_context()
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'

**Comment by Smelltastic** [comment]
I think you guys are having the issue described in https://github.com/knulli-cfw/distribution/issues/169, not this one. This is a different issue with software lists.

Also, after implementing the updated non-overlay fix on https://github.com/knulli-cfw/distribution/issues/169 that ben-willmore offered and removing the filesystem overlay with the directory link in it, I'm only seeing crashes if I actually set a software list option, left on "Auto" it seems to runs fine. So either I messed something up testing, or maybe MAME 0.268 fixed some problem 0.265 had.

I believe the software lists may be required for some games though, and it seems to be looking in the wrong place for them, so I do still think addressing that would be helpful.

**Comment by joaopedropio** [comment]
I'm having this issue when trying some ports. I'm running knulli firefly 2024/12/04, using 2 SDs: the second one is exFat. Didn't have to time to test with ext4.

```
error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
error: invalid command currentMode
/usr/bin/batocera-resolution listOutputs
/usr/bin/batocera-resolution currentResolution
/usr/bin/batocera-resolution setOutput
/bin/sh: 1: batocera-mouse: not found
Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 456, in <module>
    do_new_context(new_context_name, new_context_json)
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
2024-12-25 21:00:28,448 ERROR (emulatorlauncher.py:504):runCommand 
Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 458, in <module>
    do_new_context()
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
/bin/sh: 1: batocera-mouse: not found
```

**Comment by Smelltastic** [comment]
> I'm having this issue when trying some ports. I'm running knulli firefly 2024/12/04, using 2 SDs: the second one is exFat. Didn't have to time to test with ext4.

This ticket is for an issue running MAME-related cores with a software list set. If you're having a problem running ports, you should check the discord for support or open a separate ticket describing your issue.
