### ISSUE TITLE
Long press game menu stopped working

### ISSUE THREAD

**Issue by flowchartsman** [knulli-cfw/distribution#230]
### Knulli build version

firefly 2024/12/04 18:24

### Your architecture

TrimUI Brick

### Issue description

All of the sudden, I am no longer able to hold the button to run the game in order to bring up the game options. It was working earlier today, but now it does nothing. If I hold down the button and then release, it simply runs the game. I am no longer able to scrape individual games.

### Detailed reproduction steps

I am unsure how to reproduce this issue as I cannot restore the correct behavior to bisect the cause.

### Details of any attempts to fix this yourself

- full power cycle
- refresh game list
- system settings -> frontend developer options -> clean gamelists & remove unused media
- system settings -> frontend developer options -> switch confirm & cancel buttons in emulationstation -> off
  - This swaps the buttons so that south button ("B" on my device) runs the game, however the long press to open game options still does not work 
- system settings -> frontend developer options -> access game options with north button
  - this restores the functionality of accessing game options with the north button ("X" on my device), but then save states are inaccessible (presumably because they now require a long press on the east button ("A" on my device), which is the broken functionality. This indicates that it is the long press on game options which is busted and not any particular button handling.

### Details of any modifications you have made to Knulli.

Added some new systems (and US-region aliases for existing systems) following the instructions here: https://www.reddit.com/r/SBCGaming/comments/1deka3d/easily_add_these_missing_systems_to_knulli_with/

This involves three steps:
- **Step 1:** add the following lines to the end of `/userdata/system/batocera.conf`

```
arcade.core=fbneo
arcade.emulator=libretro
cps1.core=fbneo
cps1.emulator=libretro
cps2.core=fbneo
cps2.emulator=libretro
cps3.core=fbneo
cps3.emulator=libretro
genesis.core=genesisplusgx
genesis.emulator=libretro
megadrivejp.core=genesisplusgx
megadrivejp.emulator=libretro
sfc.core=snes9x
sfc.emulator=libretro
tg16.core=pce_fast
tg16.emulator=libretro
tg16cd.core=pce_fast
tg16cd.emulator=libretro
```
 
- **Step 2:** place [new system configuration files](https://github.com/user-attachments/files/18249452/new_system_configs.zip) in ` /userdata/system/configs/emulationstation` (these are attached to the issue, but seem fairly straightforward)
- **Step 3:** add the following 9 folders to `/userdata/roms`:
  - `arcade`
  - `cps1`
  - `cps2`
  - `cps3`
  - `genesis`
  - `megadrivejp`
  - `sfc`
  - `tg16`
  - `tg16cd` 

Following this I simply:
- moved contents of `userdata/roms/pcengine` -> `userdata/roms/tg16`
- moved contents of `userdata/roms/megadrive` -> `userdata/roms/genesis`

Primarily this has had the effect that now my systems include "Turbografix 16" and "Sega Genesis" instead of "PC-Engine" and "Sega Megadrive", which I prefer, having grown up in the US region.

The other new systems are empty, save for "arcade", which contains one MAME game, as a test, since the built-in mame did not work with it. Now it does.
 
### Logs and data

The following log entry from `es_launch_stderr.log` seems like it might be relevant:

```
Traceback (most recent call last):
  File "/usr/bin/hotkeygen", line 458, in <module>
    do_new_context()
  File "/usr/bin/hotkeygen", line 288, in do_new_context
    pid = int(read_pid())
              ^^^^^^^^^^
  File "/usr/bin/hotkeygen", line 272, in read_pid
    with GPID_FILE.open() as fd:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/hotkeygen.pid'
```

It is the only traceback in the file. Everything else looks relatively ordinary.

### Other

I briefly enabled syncthing via services and disabled it later if this is meaningful.

**Comment by flowchartsman** [comment]
One more observation: this seems to be connected to the theme somehow.  If I change the theme from `ES-THEME-ART-BOOK-NEXT` to `ES-THEME-KNULLI` the long press for game options works again. It partially works  with `ES-THEME-CARBON`; however it won't fire unless I press left or right while the button is held down. It then brings up the game options for the newly-highlighted game.

**Comment by A-L** [comment]
I also have this issue, for now I have just applied the button swap – RG35XX Plus.

**Comment by c64chrom** [comment]
This does not affect Anbernic RG40XX H/V

**Comment by Rinka-Sei** [comment]
With my RG35XXSP, I've found that the game options are only accessible when using the default `ES-THEME-KNULLI` theme. This necessitates a temporary switch to that theme to add ROMs to my favorites, which is a minor, albeit occasional, inconvenience.
