### ISSUE TITLE
[RG35XX Plus] Wifi not working

### ISSUE THREAD

**Issue by steilerDev** [knulli-cfw/distribution#32]
### Knulli build version

40-dev-d8b86623f3 2024/05/30 01:50

### Your architecture

RG35XX Plus

### Issue description

When trying to find nearby Access Points, the "Scanning..." modal only briefly appears and no APs can be found.

Manually inserting SSID and PSK did not work either.

### Detailed reproduction steps

1. Fresh install
2. Go to Network Settings
3. Search for nearby AP
4. No AP shows up - manual connection to SSID is not working either

### Details of any attempts to fix this yourself

- Disabled WPA3 on AP
- Disabled 5GHz on AP
- Tried different AP

### Details of any modifications you have made to Knulli.

Fresh install.

### Logs and data

Since I had no success accessing the terminal locally on the device, I was only able to run very simple scripts to get data off the device. Attached is `dmesg` output, but let me know what else would be useful.
[log.txt](https://github.com/user-attachments/files/15524800/log.txt)

**Comment by elkinjosetm** [comment]
I'm having the same issue here on my new RG35XX Plus, I've been doing all kind of stuff as this is my first time with the device

**Comment by steilerDev** [comment]
I was able to establish shell access to the device (through an ethernet to USB-C adapter).

A couple of findings:

- No wifi interface shows up in `ip a`:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0@NONE: <BROADCAST,MULTICAST,DYNAMIC> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
6: ip6_vti0@NONE: <NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1
    link/tunnel6 :: brd ::
7: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
8: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1
    link/tunnel6 :: brd ::
9: eth0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:e0:4c:68:02:4f brd ff:ff:ff:ff:ff:ff
    inet 10.13.0.233/24 brd 10.13.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2003:ee:372b:7c03:2e0:4cff:fe68:24f/64 scope global dynamic mngtmpaddr 
       valid_lft 86364sec preferred_lft 14364sec
    inet6 fe80::2e0:4cff:fe68:24f/64 scope link 
       valid_lft forever preferred_lft forever
```

- `batocera-scanlist` returns immediately and empty
- `iw dev` returns empty
- I can see that there is a wlan module available in `/sys/firmware/devicetree/base/soc@03000000/wlan`

Not sure where to go from here - let me know how I can debug this further

Edit: `cat /sys/firmware/devicetree/base/model` gives me `sun50iw9` - not sure if this is maybe different to other RG85XX+?

**Comment by acmeplus** [comment]
Try to run lsmod to see if the wireless drivers are being loaded. You can also run dmesg and upload the output here.

**Comment by steilerDev** [comment]
```
[root@KNULLI /userdata/system]# lsmod
Module                  Size  Used by
rtl_btlpm              16384  0
8821cs               2691072  0
mali_kbase            503808  7
squashfs               65536  1
```

`dmesg` log attached. 
[dmesg-2024-06-10.log](https://github.com/user-attachments/files/15757189/dmesg-2024-06-10.log)


btw - I noticed Bluetooth does not seem to work either (from `/var/log/bluetooth-agent.log`:
```
2024-06-10 10:13:00,991 agent registered
2024-06-10 10:13:06,006 agent fails
2024-06-10 10:13:06,007 Bluetooth adapter not found
Traceback (most recent call last):
  File "/usr/bin/batocera-bluetooth-agent", line 435, in do_main_loop
    adapter = bluezutils.find_adapter(dev_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/bluezutils.py", line 14, in find_adapter
    return find_adapter_in_objects(get_managed_objects(), pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/bluezutils.py", line 26, in find_adapter_in_objects
    raise Exception("Bluetooth adapter not found")
Exception: Bluetooth adapter not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/batocera-bluetooth-agent", line 501, in <module>
    do_main_loop(options.dev_id)
  File "/usr/bin/batocera-bluetooth-agent", line 438, in do_main_loop
    adapter = bluezutils.find_adapter(None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/bluezutils.py", line 14, in find_adapter
    return find_adapter_in_objects(get_managed_objects(), pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/bluezutils.py", line 26, in find_adapter_in_objects
    raise Exception("Bluetooth adapter not found")
Exception: Bluetooth adapter not found
```

Thanks for looking into this!

**Comment by diegombeltran** [comment]
Disabling 802.11w Management Frame Protection works for me.

This is my OpenWrt AP configuration:
![imagen](https://github.com/knulli-cfw/distribution/assets/7081281/3fe8a453-c4ab-4ac2-aed6-ef416605a60a)

**Comment by steilerDev** [comment]
All of this is already disabled :/

**Comment by jajadannn** [comment]
Having the same problem here, has someone found something?

**Comment by jajadannn** [comment]
I found that when I make an Hotspot over my PC with the 2.4Ghz Band it works just fine.
In 5Ghz mode it works too. Could someone try to use an Router without an Mesh connection?

**Comment by steilerDev** [comment]
I'm 99% confident that the issue I am facing is on the Anbernic and not my network - there are a few networks around me, including very badly secured 2.4ghz ones from my neighbours, the device is not able to see any of them (I'm not even trying to connect to them)

**Comment by jajadannn** [comment]
I know, but why does it work with WPA3 and 5Ghz on my PC Hotspot and not on my local Network

**Comment by steilerDev** [comment]
Maybe @diegombeltran's input could help you @jajadannn - but I think your issue is distinct from mine and should be handled in a separate issue.

**Comment by Dreadlocke12** [comment]
Have the same issue. Connecting to hotspot works but not when connecting to my home wifi unless i remove the wpa2 authentication and have an unprotected wifi.

**Comment by Dreadlocke12** [comment]
I tested a few custom os and this seems to be the same issue in the previous battocera build i think it was 40 as well and on the stock os. In Muos i can connect to the same wifi though if that helps.

**Comment by smoya** [comment]
Same issue with the RG40XX H. I tried all security modes (WPA, WPA 2, 3 and their variants) and it only works when removing security completely. No matter if it is 2.5 GHz or 5 GHz.

**Comment by IM0001GT** [comment]
Need to bump this as I'm a little puzzled as well. Have both an 35XXH and Plus and both cannot seem to connect to my Ubiquiti WPA2/3 network. Even when I drop the network down to just WPA2 it doesn't want to connect. Doing the same to my Pixel 9's WPA3 hotspot works fine though as others have had similar luck. 

Going to do a few more test and see if I can narrow it down to any one setting on the network but as it's a WiFi 7 network, this is going to grow into a larger issue over time as networks evolve.

**Comment by Dreadlocke12** [comment]
I have as well a Ubiquiti Access Point and for me it works without using any password with MAC Adress authentication. Not the best solution but better than no connection.

**Comment by IM0001GT** [comment]
> I have as well a Ubiquiti Access Point and for me it works without using any password with MAC Adress authentication. Not the best solution but better than no connection.

This is pretty much the only way I can seem to get it to work as well. Created a new WiFi network and even with all the optimizations or other settings disabled, the RG35XX*'s will not connect to the network if it has any security on it. They also seem to have issues connecting if the network is Hidden. Only having it Open and enabling MAC Address Filtering seems to be a way to secure the network while allowing them to connect. 

The weird thing too is the H seems to be a little different than the Plus in how it's WiFi works. The Plus was being a real sticker trying to get it to connect AND pull an IP, while the H just hopped on and worked just fine. After some tinkering and setting a static IP from my Ubiquity Gateway, the Plus finally decided to play nice after like an hour of fiddling. 

Overall, I would like to dig more into this to possibly see why this is happening and why it's having so much trouble. Heck I'd like to see the MAC address and set an IP manually from in the OS as well but that can come whenever.

 The only other device in my house having any issues with this network is an old Surface Pro 3 with the old Marval AVASTAR AC adapter that had issues with the old drivers, but a new 2021 driver fixed that right up.

**Comment by lanmarc77** [comment]
I have the same issue. No wireless connection. After logging in the same sneaky way like @steilerDev I could also see that there is no wireless interface. If there is no interface then I do not see how changing wireless hotspot settings would help.
I am using the version firefly.
As others seem to be able to connect I can only assume that there could be different hardware revisions. I attach a picture of the back sticker of my model.
![RG35XX+](https://github.com/user-attachments/assets/50e5fac2-55e0-4096-8816-1d8e966cae0d)

EDIT:
I think this is a marketing mess up. The packaging box says RG35XX 2024. This model does not have wireless modules. @steilerDev if you have the same sticker and box packaging this might apply to your model as well.

**Comment by timskillbridge** [comment]
Like so many, I had issues with my wifi on the RG35XX connecting to anything which wasn't a completely open network.

I solved my issue on both of my devices.
I can't assure it will work for you but it does for me.

In settings, turn off wifi fix and wifi dongle if enabled. then restart.
Go to network settings and try to connect to your network of choice; it will fail.
Go back to settings, turn both wifi dongle and wifi fix  on.  I know the dongle shouldn't matter but it does for some reason.
Go back to the main menu and then press select, turn off plane mode.
Go to ports, launch portmaster.  It should connect and download the update it needs.

Exit port master, wifi connected, maintains through reboot.

This may require you connecting to an open network to install portmaster before doing all of these steps.

The wifi I am connecting to is a 5Ghz band using WPA2 Personal, AES and TKIP, Frame protection management disabled, strict rekeying disabled; it's a basic setup.

Hope it works for you

**Comment by SinnedNima** [comment]
> Like so many, I had issues with my wifi on the RG35XX connecting to anything which wasn't a completely open network.
> 
> I solved my issue on both of my devices. I can't assure it will work for you but it does for me.
> 
> In settings, turn off wifi fix and wifi dongle if enabled. then restart. Go to network settings and try to connect to your network of choice; it will fail. Go back to settings, turn both wifi dongle and wifi fix on. I know the dongle shouldn't matter but it does for some reason. Go back to the main menu and then press select, turn off plane mode. Go to ports, launch portmaster. It should connect and download the update it needs.
> 
> Exit port master, wifi connected, maintains through reboot.
> 
> This may require you connecting to an open network to install portmaster before doing all of these steps.
> 
> The wifi I am connecting to is a 5Ghz band using WPA2 Personal, AES and TKIP, Frame protection management disabled, strict rekeying disabled; it's a basic setup.
> 
> Hope it works for you

i tried that but no luck on rg35xx h

**Comment by SinnedNima** [comment]
as i replied to you @timskillbridge  i somehow connected to my guest network. I disabled WPA3 on home and guest. Home has a password with more than 8 characters. i realised while visiting those setting during exercise of your guide, that sometimes the rest of my home wifi pasword was missing. so i tried to connect/reconnect with your guide again but this time to my guest network with 8 character password - low and behold! connected.

edited:
albeit the euphoria i experienced, this setup is not persistent. After reboot no reconnect.
Nothing can be done to force to connect to the home network.

damn, wanted to gift my daughter the rg35xx h so we can netplay with my rg-cubexx - no issues on that device (if hybrid fix applied and WPA3 disabled)

Hope this get sorted out soon.

**Comment by devallabharath** [comment]
I have Xfinity Wi-Fi router that combines both 2.4 GHz and 5 GHz bands, sharing the same SSID and password for both. All my devices, including my phone, computer, and various smart IoT(2.4ghz) devices, are able to connect to my Wi-Fi network without any issues. However, my RG35XX Pro device was unable to connect to the Wi-Fi network, but it was able to connect to my iPhone hotspot. Recently, I attempted to install REGLINUX on my device. Although REGLINUX lacks several features and functionalities, it offers excellent connectivity capabilities. The Wi-Fi and hotspot connections are seamless, and I can use Samba, SSH, and etc without any problems.

I beleive the REGLINUX is an open-source project. Better analyze how the networking is handled in REGLINUX. Personally I like the Knulli OS among the current alternatives and hoping a fix for network connections soon.
